# Étape de build
FROM node:18 as build-stage

WORKDIR /app

COPY ./client/package.json ./client/yarn.lock* /app/

RUN yarn install --frozen-lockfile

COPY ./client/ /app/

RUN yarn build

FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
