FROM python:3.8

WORKDIR /app

COPY ./server/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./server /app

RUN mkdir -p /app/node/index /app/node/extracted_texts /app/node/files

ENV UVICORN_ENV "production"

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
